#!/usr/bin/python3


def raise_exception_msg(message=""):

    try:
        raise raise_exeption_msg
    except NameError:
        print(message)
